### PR TITLE
Make baseline searches case insensitive

### PR DESCRIPTION
**Pull request by CodeHeeler**

### CODE REVIEW

**Review by eherget — COMMENTED** [review]
If the SystemBaseline.display_name value has uppercase characters, I think this may miss.  Checkout https://stackoverflow.com/questions/16573095/case-insensitive-flask-sqlalchemy-query for possible ways to do case insensistive query for both values.

**Comment by CodeHeeler** [comment]
> If the SystemBaseline.display_name value has uppercase characters, I think this may miss. Checkout https://stackoverflow.com/questions/16573095/case-insensitive-flask-sqlalchemy-query for possible ways to do case insensistive query for both values.

how about this change (just pushed up) instead?  Would it be preferable to use the little bit of storage ahead of the query to doing a more complicated query or vice versa when considering both efficiency and future readability?

**Comment by eherget** [comment]
> > If the SystemBaseline.display_name value has uppercase characters, I think this may miss. Checkout https://stackoverflow.com/questions/16573095/case-insensitive-flask-sqlalchemy-query for possible ways to do case insensistive query for both values.
> 
> how about this change (just pushed up) instead? Would it be preferable to use the little bit of storage ahead of the query to doing a more complicated query or vice versa when considering both efficiency and future readability?

I would only use func.lower() on the SQLAlchemy object.  Use the python string's .lower() method on the value passed in to the function/query.  I don't know if SQLAlchemy is smart enough to optimize the second func.lower() or if it will have to evaluate it with each result.  So "...contains(display_name.lower())" may be more readable and at least as performant.

Are you able to run this locally to test it?

**Review by eherget — APPROVED** [review]
This looks good, I think.  Just need to get the black check to pass.  Approved.

**Pull request merged**
