### PR TITLE
Updates watchtower to use new code in kerlescan

### PR DESCRIPTION
**Pull request by petrblaho**
## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by petrblaho** [comment]
@radohanculak

**Comment by petrblaho** [comment]
https://github.com/RedHatInsights/kerlescan/pull/79

**Review by CodeHeeler — APPROVED** [review]
LGTM

**Comment by petrblaho** [comment]
Core developers are on PTO, merging with approval from others :-)

**Pull request merged**
