### PR TITLE
[DRFT-816] Add account_number filter to delete_by_system_ids query

### PR DESCRIPTION
**Pull request by jpramos123**
## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by petrblaho — APPROVED** [review]
LGTM!

**Comment by sthirugn** [comment]
thank you for the PR. Is there a need for 2 different commits in this PR? could they have been squashed?

**Comment by petrblaho** [comment]
It is already merged.

But we should for sure keep unrelated changes in separate PRs in the future.

**Comment by sthirugn** [comment]
ack yes

**Comment by jpramos123** [comment]
Ack!

**Pull request merged**
