### PR TITLE
[DRFT-1111] org_id db migration - column creation

### PR DESCRIPTION
**Pull request by petrblaho**
- Adds org_id column to system_baselines
- Adds org_id column to system_baseline_mapped_systems

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by petrblaho** [comment]
We can check that it works by using remote shell (`oc rsh`) with ephemeral to connect to a pod running db for the service and using `psql` to see the new structure of the db / tables.

**Review by CodeHeeler — APPROVED** [review]
Looks good to me.  Alembic.op usage looks accurate.

**Comment by CodeHeeler** [comment]
> We can check that it works by using remote shell (`oc rsh`) with ephemeral to connect to a pod running db for the service and using `psql` to see the new structure of the db / tables.

Assuming after this migration is verified, then you'll run the populator tool and check the values for validation?

**Comment by petrblaho** [comment]
> 

Yes, first migration of db structure (this PR), then org-id-populator-job definition.
We can run the job in ephemeral by ourselves manually, for stage and production we need further config changes and an action done by authorized person. Unfortunately we will not see the db structure change on stage and production as devs don't have access to terminal and we did not set up gabi.

**Comment by jpramos123** [comment]
Hey @petrblaho thanks for the PR!

LGTM!

And we have gabi running in stage for baseline (but not for HSP)

**Review by jpramos123 — APPROVED** [review]

**Pull request merged**
